####Getting & Cleaning Data Quiz 2

##Question 1

#load packages
library(httr)
library(httpuv)
library(jsonlite)

#key & secret generated by github app
myapp = oauth_app("github",
                  key="01bb144ed24723cdcbd3",secret="42a49f013950f3a8092059642bddf775a8fcb82c")

#Get OAuth cred
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
gtoken <- config(token = github_token)

#get repos using API
req <- GET("https://api.github.com/users/jtleek/repos", gtoken)
stop_for_status(req)


content(req)
json1 = content(req)
list(json1[[5]]$name, json1[[5]]$created_at)

#transform to data table
json2 = jsonlite::fromJSON(toJSON(json1))
#transform to data table
json2 = jsonlite::fromJSON(toJSON(json1))
json2$name
json2[5,]
json2[5,]$created_at


### Question 2

library(sqldf)
acs <- read.csv("Getting & cleaning data/getdata-data-ss06pid.csv", header=T, sep=",")
head(acs)
sqldf("select * from acs where AGEP < 50 and pwgtp1")
sqldf("select * from acs where AGEP < 50")
sqldf("select * from acs")
sqldf("select pwgtp1 from acs where AGEP < 50")


###Question 3
##Using the same data frame you created in the previous problem, what is the equivalent function to unique(acs$AGEP)
sqldf("select distinct AGEP from acs")



###Question 4

con = url("http://biostat.jhsph.edu/~jleek/contact.html")
htmlCode = readLines(con)
close(con)
htmlCode
sapply(htmlCode[c(10,20,30,100)],nchar)


###Question 5
dat<-read.fwf("./Getting & cleaning data/getdata-wksst8110.for",widths=c(12, 7,4, 9,4, 9,4, 9,4),header=FALSE,skip =4)
sum(dat[,4])

