####Getting & Cleaning Data Quiz 2

##Question 1

#load packages
library(httr)
library(httpuv)
library(jsonlite)

#key & secret generated by github app
myapp = oauth_app("github",
                  key="01bb144ed24723cdcbd3",secret="42a49f013950f3a8092059642bddf775a8fcb82c")

#Get OAuth cred
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
gtoken <- config(token = github_token)

#get repos using API
req <- GET("https://api.github.com/users/jtleek/repos", gtoken)
stop_for_status(req)


content(req)
json1 = content(req)
list(json1[[5]]$name, json1[[5]]$created_at)

#transform to data table
json2 = jsonlite::fromJSON(toJSON(json1))
json2[1,1:4]
